version: 2
updates:
#######################################################
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@agentica/*"
      - dependency-name: "@samchon/*"
      - dependency-name: "openai"
      - dependency-name: "@nestia/*"
      - dependency-name: "nestia"
      - dependency-name: "tstl"
      - dependency-name: "typia"
      - dependency-name: "tgrid"
      - dependency-name: "typescript"
      - dependency-name: "typescript-transform-paths"
      - dependency-name: "ts-patch"
    groups:
      Agent:
        patterns:
          - "@agentica/*"
          - "@samchon/*"
          - "openai"
          - "@nestia/*"
          - "nestia"
          - "tstl"
          - "typia"
          - "tgrid"
      TypeScript:
        patterns:
          - "typescript"
          - "typescript-transform-paths"
          - "ts-patch"
#######################################################
  - package-ecosystem: 'npm'
    directory: '/packages/api'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@nestia/fetcher"
      - dependency-name: "typia"
      - dependency-name: "tgrid"
    groups:
      Samchon:
        patterns:
          - "@nestia/fetcher"
          - "typia"
          - "tgrid"
#######################################################